layout_spectrum: 0.7639123
color:
  saturation: 0.215534
  lightness: 0.3022549
  brandStrength: 0.2539622
  brandColors:
    - '#E9E5D9'
    - '#8A5B3D'
    - '#4F2B1B'
    - '#AC805D'
    - '#070709'
  rhythmicContrast: 0.1753178
typography_spectrum: 0.1568297
name: AndrewJohnMitchell
